# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Lilac Walk
email: alex@goldenmeanie.net
description: > # this means to ignore newlines until "baseurl:"
  A very local map of lilac bushes in Providence, RI that are accessible from the sidewalk.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://goldenmeanie.net/lilac-walk" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
